# Nylo - Micro-framework for Flutter.
#
# Website: https://nylo.dev
# Official repository: https://github.com/nylo-core/nylo
# Author: Anthony Gordon <https://github.com/agordn52>

name: flutter_app
description: Tercuman Bul!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  url_launcher: 6.1.9
  google_fonts: 4.0.3
  intl: 0.17.0
  nylo_framework: 4.1.2
  pretty_dio_logger: 1.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.5
  flutter_chip_tags: 2.0.2
  firebase_core: 2.5.0
  firebase_ui_auth: 1.1.11
  responsive_framework: 0.2.0
  firebase_ui_oauth_google: 1.0.18
  json_annotation: 4.8.0
  cloud_firestore: 4.4.0
  syncfusion_flutter_datagrid: 20.4.50
  expandable: 5.0.1
  material_design_icons_flutter: 6.0.7096
  flutter_localized_locales: 2.0.4
  dash_flags: 0.0.3
  diacritic: 0.1.3
  google_sign_in: 5.4.4
  dropdown_search: 5.0.5
  flutter_linkify: 5.0.2
  location: 4.4.0

dev_dependencies:
  build_runner: 2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: 6.6.1
  lint: 2.0.1
  freezed: 2.3.2
  freezed_annotation: 2.2.0
  analyzer: 5.5.0
  change_app_package_name: 1.1.0

# APP ICON - public/assets/app_icon/icon.png
# Build icons: "flutter pub run flutter_launcher_icons:main"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/assets/fonts/
    - public/assets/images/
    - public/assets/app_icon/
    - lang/
    - .env
    - public/assets/data/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#   fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
